language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq octave octave-pkg-dev
  # Setup Anaconda.
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself.
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda.
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose
  - source activate env_name
  # Not in anaconda.
  - pip install oct2py
  - python setup.py install
script:
  - cd gsw/test && nosetests --verbose --nocapture
