language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - ci/before_install.sh
  - pip install --use-mirrors numpy
  - pip install --use-mirrors scipy
  - pip install --use-mirrors oct2py

install:
  - python setup.py install

script:
  - cd gsw/test
  - nosetests --verbose --nocapture

branches:
  only:
    - master

notifications:
  email: false
