language: python

env:
    - CONDA="python=2.7"
    - CONDA="python=3.3"
    - CONDA="python=3.4"


before_install:
    - sudo apt-add-repository -y ppa:picaso/octave
    - sudo apt-get update -qq
    - sudo apt-get install -qq octave liboctave-dev
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes
    - conda update conda
    - conda info -a
    - travis_retry conda create -n test $CONDA numpy pip nose scipy
    - source activate test
    - travis_retry pip install oct2py
    - travis_retry pip install pytest
    - travis_retry pip install coveralls
    - travis_retry pip install pytest-cov

install:
    - export PYTHONWARNINGS=all
    #- python setup.py install

script:
    - if [[ $CONDA == python=2.7* ]]; then
        py.test ;
      else
        py.test ;
      fi

after_success:
    - coveralls
