language: python

sudo: false

env:
  global:
    - secure: "DdUE82IkNYo317595sy4H6z3GQoaVUTAAUDOOoJATa199ERxSQy8VlsMKELdRTrBEt76kSBJdjjJ7YSiOVSMt9qao9XWOWYjtfdX0KpbkmfiHMH6fmQnckNndMbPY8wa42fFusIWOxZL/jCay1Gq0GppjoHdSoaLGIk3hLkYE1U="

addons:
  apt:
    packages: octave

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: NUMPY=1.11
  - python: 2.7
    env: NUMPY=1.12
  - python: 3.6
    env: NUMPY=1.11
  - python: 3.6
    env: NUMPY=1.12
  - python: 3.6
    env: TEST_TARGET=publish

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - conda config --add channels conda-forge --force
    - conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements-dev.txt
    - source activate TEST
    - conda install --yes numpy=$NUMPY
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
        conda install --yes doctr ;
      fi

# Test source distribution.
install:
    - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install gsw-${version}.tar.gz && popd

script:
    - py.test -vv
    - if [[ $TEST_TARGET == "publish" ]]; then
        pushd docs && make html && popd
        doctr deploy --built-docs=docs/_build/html --gh-pages-docs=. ;
      fi
